#===================================================================
# 기본 설정
#===================================================================
spring:
  profiles:
    active: local

application:
  name: welper-back    




---
# ==================================================================
# local
# ==================================================================
spring:
  config:
    activate:
      on-profile: local
  application:
    name: welper-back
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

  datasource:
    url: "jdbc:mysql://localhost:3306/welper"
    username: "root"
    password: ${DB_LOCAL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver



---
# ==================================================================
# prod
# ==================================================================
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false