#===================================================================
# 기본 설정 (공통)
#===================================================================
spring:
  profiles:
    active: local
  # 음성 파일 size 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

application:
  name: welper-back

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000 # 1시간
  refresh-expiration: 604800000 # 7일

ai:
  model:
    url: ${AI_MODEL_URL} # 호출할 AI 모델 주소

# ==================================================================
# 파일 업로드 설정、 이 부분이 고민 되는데（AWS S3 사용 여부 결정해야함, 구조상 보이스 파일을 로컬에 저장하는 걸로 우선 했음)
# ==================================================================
file:
  upload-dir: ${FILE_UPLOAD_DIR}

springdoc:
  swagger-ui:
    path: /swagger

welper:
  server:
    base-url: "http://localhost:8000"


---
# ==================================================================
# local (개발용)
# ==================================================================
spring:
  config:
    activate:
      on-profile: local

  application:
    name: welper-back

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

  datasource:
    url: "jdbc:mysql://localhost:3306/welper"
    username: "root"
    password: ${DB_LOCAL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# ==================================================================
# prod (운영용)
# ==================================================================
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

welper:
  server:
    baes-url: http://api.welper.store
